checkpoint:
  filename: best_scc_model.pth
model:
  theta_dim: 126
  beta_dim: 10
  hidden_dim: 512
  K: 8
  num_layers_g0: 12
  num_layers_phi: 6
  num_layers_shape: 4
optimization:
  max_itr: 100
  threshold: 0.05
  resolved_tolerance: 0.005
example:
  examples_path: demo_examples.json
  example_idx: 0
